[package]
name = "latex-figures"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
log = "0.4.6"
tracing-subscriber = "0.3"
tracing = "0.1.37"
itertools.workspace = true
num = "0.4.0"
md5 = "0.7.0"
pxu = { path = "../pxu" }
make-paths = { path = "../make-paths" }
indicatif = "0.17.3"
clap = { workspace = true, features = ["derive"] }
threadpool = "1.8.1"
num_cpus = "1.15.0"
ron = "0.8.0"
flo_curves = "0.7.2"
